// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvuvfagnncposonvvway.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2dXZmYWdubmNwb3NvbnZ2d2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTcwNDgsImV4cCI6MjA2MzkzMzA0OH0.GWZKqAEWLtK3CpNUydKMLf3Y7wIp1yB2NclPOHLguOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);